markup:
  - 'replace'
  - 'assemble'
  - 'htmlmin'

media:
  - 'imagemin'
  - 'svgmin'
  - 'copy:images'
  - 'copy:svg'
  - 'copy:videos'

devstyles:
  - 'scsslint'
  - 'sass'
  - 'autoprefixer:critical'
  - 'autoprefixer:dev'

productionstyles:
  - 'sass'
  - 'autoprefixer:critical'
  - 'autoprefixer:production'

server:
  - 'browserSync'
  - 'watch'

dev:
  - 'config:dev'
  - 'clean:build'
  - 'devstyles'
  - 'markup'
  - 'media'
  - 'jshint'
  - 'copy:javascript'
  - 'clean:temp'
  - 'server'

deploy:
  - 'config:production'
  - 'clean:build'
  - 'productionstyles'
  - 'markup'
  - 'media'
  - 'jshint'
  - 'copy:javascript'
  - 'clean:temp'

default:
  - 'dev'
